module Graphics.D3D11Binding.Interface.D3D11RenderTargetView where

import Graphics.D3D11Binding.Interface.Unknown

data ID3D11RenderTargetView = ID3D11RenderTargetView

instance UnknownInterface ID3D11RenderTargetView