module Graphics.D3D11Binding.Interface.D3D11DepthStencilView where

import Graphics.D3D11Binding.Interface.Unknown
import Graphics.D3D11Binding.Interface.D3D11Resource

data ID3D11DepthStencilView = ID3D11DepthStencilView

instance UnknownInterface ID3D11DepthStencilView

instance D3D11ResourceInterface ID3D11DepthStencilView